### ISSUE TITLE
Lab 3 - says data importer doesn't support properties on relationships

### ISSUE THREAD

**Issue by Samyouell** [neo4j-partners/hands-on-lab-neo4j-and-vertex-ai#15]
That may have been true for an old version of Data Importer, but it is now able to set relationship properties.
Suggest you remove that line.

**Comment by benofben** [comment]
Changed.  I'm still wondering if data importer should be part of the labs.  The answer is probably yes.  I kinda of thing three load exercises would be too many, so haven't done it this go round.
