### ISSUE TITLE
Lab 4 - having a hard time pasting my DB id and DB pw into the notebook

### ISSUE THREAD

**Issue by Samyouell** [neo4j-partners/hands-on-lab-neo4j-and-vertex-ai#17]
Although I can delete characters and manually type characters, the ability to paste is very wonky.  I eventually got it to work, but I don't know why it finally allowed me to paste.

**Comment by benofben** [comment]
I'm really confused about this one.  I'm on a Mac with Chrome and have never had an issue.  What does your environment look like?

**Comment by gogitguhan** [comment]
Now the Jupyter script will be asking for input from users.

**Comment by gogitguhan** [comment]
Tested in Chrome and Safari.
