### ISSUE TITLE
Lab 5 - upload to google cloud storage

### ISSUE THREAD

**Issue by Samyouell** [neo4j-partners/hands-on-lab-neo4j-and-vertex-ai#19]
This step gives me an error message that mentions "bucket.location" is deprecated".  Did google code change?
I'm not sure if I'm doing the step right or not.

Full error message:

<ipython-input-17-e4db9dd388a4>:2: DeprecationWarning: Assignment to 'Bucket.location' is deprecated, as it is only valid before the bucket is created. Instead, pass the location to `Bucket.create`.
  bucket.location=REGION
---------------------------------------------------------------------------
TransportError                            Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py in refresh(self, request)
    110         try:
--> 111             self._retrieve_info(request)
    112             self.token, self.expiry = _metadata.get_service_account_token(

15 frames
TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f544792bca0>)

The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/six.py in raise_from(value, from_value)

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f544792bca0>)

**Comment by gogitguhan** [comment]
Fixed the deprecation warning message.

**Comment by benofben** [comment]
Thanks Guhan.  Confirmed it's fixed!
